// Generated by CoffeeScript 1.6.3
(function() {
  var Renderer;

  window.Renderer = Renderer = (function() {
    function Renderer(canvas_context) {
      this.ctx = canvas_context;
    }

    Renderer.prototype.render = function(world) {
      this.ctx.fillStyle = "#000000";
      this.ctx.fillRect(0, 0, 800, 600);
      this.render_player(world.p1, "#00ff00");
      this.render_player(world.p2, "#ff00ff");
      return this.ctx.fillStyle = "#000000";
    };

    Renderer.prototype.render_player = function(player, color) {
      this.ctx.fillStyle = color;
      this.ctx.fillRect(player.x, player.y, 50, 30);
      return this.ctx.fillStyle = "#000000";
    };

    return Renderer;

  })();

}).call(this);
