// Generated by CoffeeScript 1.6.3
(function() {
  var render, render_player;

  render = function(world) {
    ctx.fillStyle = "#000000";
    ctx.fillRect(0, 0, 800, 600);
    render_player(world.p1, "#00ff00");
    render_player(world.p2, "#ff00ff");
    return ctx.fillStyle = "#000000";
  };

  render_player = function(player, color) {
    ctx.fillStyle = color;
    ctx.fillRect(player.x, player.y, 50, 30);
    return ctx.fillStyle = "#000000";
  };

}).call(this);
