// Generated by CoffeeScript 1.6.3
(function() {
  var Goal;

  module.exports = Goal = (function() {
    function Goal() {
      this.x = Math.floor(Math.random() * 45);
      this.y = Math.floor(Math.random() * 45);
    }

    return Goal;

  })();

}).call(this);
