// Generated by CoffeeScript 1.6.3
(function() {
  var Player, Word;

  Word = require("./word");

  module.exports = Player = (function() {
    function Player(id) {
      this.id = id;
      this.x = Math.floor(Math.random() * 45);
      this.y = Math.floor(Math.random() * 45);
      this.words = [];
    }

    Player.prototype.add_word = function(direction, word) {
      return this.words.push(new Word(direction, word));
    };

    return Player;

  })();

}).call(this);
