// Generated by CoffeeScript 1.6.3
(function() {
  var Word;

  module.exports = Word = (function() {
    function Word(direction, word) {
      this.direction = direction;
      this.word = word;
    }

    return Word;

  })();

}).call(this);
