// Generated by CoffeeScript 1.6.3
(function() {
  var Goal, Player, World;

  Player = require("./player");

  Goal = require("./goal");

  module.exports = World = (function() {
    function World() {
      this.players = [];
      this.goal = new Goal;
    }

    World.prototype.add_player = function(player) {
      return this.players.push(player);
    };

    return World;

  })();

}).call(this);
