// Generated by CoffeeScript 1.8.0
(function() {
  var Player, World;

  Player = require("./player");

  module.exports = World = (function() {
    function World() {
      this.players = [];
    }

    World.prototype.add_player = function(player) {
      return this.players.push(player);
    };

    return World;

  })();

}).call(this);
